### ISSUE TITLE
USER STORY: <Photo post page>

### ISSUE THREAD

**Issue by EL1909** [EL1909/bavarian-cristus-PP4#1]
As a **user** I can ** see photos posted by other users ** so that **i get interest on becoming a member**

## Acceptance Criteria:
- Acceptance Criteria 1:  Post are listed on home page
- Acceptance Criteria 2: 
- Acceptance Criteria 3: 

## Tasks
- [ ] Create Post Model
- [ ] Create Post View
- [ ] Insert to template
