### ISSUE TITLE
USER STORY: <Edit desired view>

### ISSUE THREAD

**Issue by EL1909** [EL1909/bavarian-cristus-PP4#18]
As a **User** I can **Crop uploaded images** so that **show only what i want to show**

## Acceptance Criteria:
- Acceptance Criteria 1: User can access cropping tools from upload and edit interfaces
- Acceptance Criteria 2: User can post image with their desired distribution

## Tasks
- [ ] Implement cropper.js 
- [ ] Writte js code to interact with UI
- [ ] Adapt CSS to integrate selection and sowing according to UI
